input {
  kafka {
    bootstrap_servers => "44.197.215.55:9092"
    topics => ["events-raw"]
    codec => "json"
    auto_offset_reset => "earliest"
    group_id => "logstash-consumer"
  }
}

filter {
  # The kafka input + json codec already parsed the JSON into fields.
  # No additional filtering needed for now.
}

output {
  elasticsearch {
    hosts => ["http://host.docker.internal:9200"]
    index => "github-events-%{+YYYY.MM.dd}"
  }

  s3 {
    region => "us-east-1"
    bucket => "dev-min-sec-pipeline-39d00ab9"
    prefix => "github-events/%{+YYYY/MM/dd}"
    time_file => 1
    codec => "json_lines"
  }

  stdout {
    codec => rubydebug
  }
}